name: 'Setup OpenStudio Environment'
description: 'Handles Checkout, Caching, Ruby, and Conan Setup'
inputs:
  platform:
    description: 'Platform identifier (e.g., ubuntu-2204-x64, windows-2022)'
    required: true
  ruby_version:
    description: 'Ruby version to install'
    required: true
  build_dir:
    description: 'Directory for the build'
    required: true
  install_qt:
    description: 'Install QtIFW (Windows and macOS)'
    required: false
    default: 'false'
  build_type:
    description: 'Build type (Release/Debug)'
    required: false
    default: 'Release'

runs:
  using: "composite"
  steps:


    - name: Prepare workspace
      shell: bash
      run: |
        git config --global --add safe.directory "$GITHUB_WORKSPACE"
        mkdir -p "$GITHUB_WORKSPACE/${{ inputs.build_dir }}"

    # --- CACHING ---
    - name: Compute conan.lock hash
      id: conan_hash
      shell: bash
      run: |
        if command -v sha256sum >/dev/null 2>&1; then
          echo "hash=$(sha256sum conan.lock | awk '{print $1}')" >> $GITHUB_OUTPUT
        else
          echo "hash=$(shasum -a 256 conan.lock | awk '{print $1}')" >> $GITHUB_OUTPUT
        fi

    - name: Restore ccache
      uses: actions/cache@v4
      with:
        path: ~/.ccache
        key: ccache-${{ runner.os }}-${{ inputs.platform }}-${{ steps.conan_hash.outputs.hash }}
        restore-keys: ccache-${{ runner.os }}-${{ inputs.platform }}-

    - name: Restore Conan cache
      uses: actions/cache@v4
      with:
        path: ~/.conan2
        key: conan-${{ runner.os }}-${{ inputs.platform }}-${{ steps.conan_hash.outputs.hash }}
        restore-keys: conan-${{ runner.os }}-${{ inputs.platform }}-

    # --- TOOLING SETUP ---
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby_version }}
        bundler-cache: true

    - name: Install Dependencies (Windows)
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        python -m pip install conan aqtinstall pytest requests
        choco install ccache -y --no-progress
        if (Get-Command ccache -ErrorAction SilentlyContinue) { ccache -M 5G }
    
    - name: Install QtIFW (Windows)
      if: runner.os == 'Windows' && inputs.install_qt == 'true'
      shell: pwsh
      run: python -m aqt install-tool windows desktop tools_ifw qt.tools.ifw.47 --outputdir C:\Qt

    - name: Install Dependencies (Mac/Linux)
      if: runner.os == 'macOS'
      shell: bash
      run: |
        # Assumes python3 is available (e.g. from pyenv setup in main workflow)
        python3 -m pip install --upgrade pip
        python3 -m pip install conan numpy aqtinstall pytest

    - name: Install QtIFW (macOS)
      if: runner.os == 'macOS' && inputs.install_qt == 'true'
      shell: bash
      run: |
        python3 -m aqt install-tool mac desktop tools_ifw qt.tools.ifw.47 --outputdir $HOME/Qt
        echo "$HOME/Qt/Tools/QtInstallerFramework/4.7/bin" >> $GITHUB_PATH

    # --- CONAN CONFIG ---
    - name: Configure Conan remotes
      shell: bash
      run: |
        conan remote add nrel-v2 https://conan.openstudio.net/artifactory/api/conan/conan-v2 --index 0--force
        conan remote update nrel-v2 --insecure
        conan remote add conancenter https://center2.conan.io --force
        conan remote update conancenter --insecure
        if [ ! -f "$HOME/.conan2/profiles/default" ]; then conan profile detect; fi

    - name: Conan install
      shell: bash
      working-directory: ${{ github.workspace }}
      run: |

        export CMAKE_POLICY_VERSION_MINIMUM=3.5

        # Determine generator based on OS
        GEN="Ninja"

        # Default arguments
        CONAN_ARGS="--output-folder=./${{ inputs.build_dir }} --build=missing -c tools.cmake.cmaketoolchain:generator=$GEN -s compiler.cppstd=20 -s build_type=${{ inputs.build_type }}"

        # [Logic] Force static linking on macOS to avoid Homebrew path issues
        # We also force it on Linux for better portability, but keep Windows dynamic
        if [ "${{ runner.os }}" == "macOS" ]; then
          CONAN_ARGS="$CONAN_ARGS -o *:shared=False"
        fi

        # Explicitly target armv8 on macos-arm64 to avoid x86_64 fallback
        if [ "${{ inputs.platform }}" == "macos-arm64" ]; then
          CONAN_ARGS="$CONAN_ARGS -s arch=armv8"
        fi

        # Run Conan
        conan install . $CONAN_ARGS
