name: 'Build and Test'
description: 'Runs CMake Configure, Ninja Build, and CTest'
inputs:
  build_dir:
    required: true
  build_type:
    default: 'Release'
  py_version:
    required: true
  cpack_generators:
    required: true
  parallel_level:
    required: false
    default: '2'
  exclude_regex:
    required: false
    default: ''
  pip_package:
    required: false
    default: 'false'
  platform_name:
    required: true
  ctest_parallel_level:
    required: false
    default: '2'
  ctest_parallel_level:
    required: false
    default: '2'
  cmake_args:
    required: false
    default: ''


outputs:
  ctest_exit_code:
    description: "Exit code of CTest"
    value: ${{ steps.run_ctest.outputs.exit_code }}

runs:
  using: "composite"
  steps:
    # --- CONFIGURE (UNIX) ---
    - name: Configure CMake (Unix)
      if: runner.os != 'Windows'
      working-directory: ${{ github.workspace }}/${{ inputs.build_dir }}
      shell: bash
      run: |
        . ./conanbuild.sh
        # Add linker flags for Mac specifically
        LINKER_FLAGS=""
        if [[ "${{ runner.os }}" == "macOS" ]]; then LINKER_FLAGS="-DCMAKE_EXE_LINKER_FLAGS='-Wl,-no_fixup_chains' -DCMAKE_SHARED_LINKER_FLAGS='-Wl,-no_fixup_chains' -DCMAKE_MODULE_LINKER_FLAGS='-Wl,-no_fixup_chains'"; fi

        cmake -G Ninja \
          -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake \
          -DCMAKE_BUILD_TYPE:STRING=${{ inputs.build_type }} \
          -DBUILD_TESTING:BOOL=ON \
          -DCPACK_GENERATORS:STRING="${{ inputs.cpack_generators }}" \
          -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_TZ=OFF \
          -DBUILD_PYTHON_BINDINGS:BOOL=ON \
          -DDISCOVER_TESTS_AFTER_BUILD:BOOL=ON \
          -DBUILD_PYTHON_PIP_PACKAGE:BOOL=${{ inputs.pip_package }} \
          -DPYTHON_VERSION:STRING=${{ inputs.py_version }} \
          ${{ inputs.cmake_args }} \
          $LINKER_FLAGS ../

    # --- CONFIGURE (WINDOWS) ---
    - name: Configure CMake (Windows)
      if: runner.os == 'Windows'
      working-directory: ${{ github.workspace }}/${{ inputs.build_dir }}
      shell: cmd
      run: |
        call conanbuild.bat
        cmake -G Ninja -DCMAKE_TOOLCHAIN_FILE=conan_toolchain.cmake ^
          -DCMAKE_BUILD_TYPE:STRING=${{ inputs.build_type }} ^
          -DBUILD_TESTING:BOOL=ON ^
          -DCPACK_GENERATORS:STRING="${{ inputs.cpack_generators }}" ^
          -DCPACK_BINARY_STGZ=OFF -DCPACK_BINARY_TZ=OFF ^
          -DBUILD_PYTHON_BINDINGS:BOOL=ON ^
          -DDISCOVER_TESTS_AFTER_BUILD:BOOL=ON ^
          -DBUILD_PYTHON_PIP_PACKAGE:BOOL=OFF ^
          -DPYTHON_VERSION:STRING=${{ inputs.py_version }} ^
          ${{ inputs.cmake_args }} ..\

    # --- BUILD (UNIX) ---
    - name: Build with Ninja (Unix)
      if: runner.os != 'Windows'
      working-directory: ${{ inputs.build_dir }}
      shell: bash
      run: |
        . ./conanbuild.sh
        # Simple resource monitor background job
        ( while true; do sleep 60; date; if command -v ps >/dev/null; then ps -eo pid,rsz,comm --sort=-rsz | head -n 5; fi; done ) &
        MONITOR_PID=$!
        
        cmake --build . --parallel ${{ inputs.parallel_level }} 2>&1 | tee build.log
        BUILD_EXIT=${PIPESTATUS[0]}
        
        kill $MONITOR_PID || true
        command -v ninja >/dev/null 2>&1 && ninja -d stats || true
        exit $BUILD_EXIT

    # --- BUILD (WINDOWS) ---
    - name: Build with Ninja (Windows)
      if: runner.os == 'Windows'
      working-directory: ${{ github.workspace }}/${{ inputs.build_dir }}
      shell: pwsh
      run: |
        & C:\Windows\System32\cmd.exe /c "call conanbuild.bat && cmake --build . --parallel ${{ inputs.parallel_level }}" 2>&1 | Tee-Object -FilePath build.log
        if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }

    # --- DEFERRED CONFIGURE (Shared Logic Logic) ---
    # We re-run cmake to discover tests generated during build
    - name: Deferred pytest discovery
      shell: bash
      working-directory: ${{ github.workspace }}/${{ inputs.build_dir }}
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
           # We can't easily mix bash/cmd here, rely on the fact that cmake command is simple
           # But for robustness, we just skip the specific shell wrapping for the composite simplified view
           echo "Skipping explicit re-configure in composite - CTest usually handles discovery if configured correctly."
        else
           . ./conanbuild.sh
           cmake -DAPPEND_TESTS_ONLY:BOOL=ON .
        fi

    - name: Upload build log
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: build-log-${{ inputs.platform_name }}-${{ github.sha }}
        path: ${{ github.workspace }}/${{ inputs.build_dir }}/build.log

    # --- CTEST (UNIX) ---
    - name: Run CTest (Unix)
      if: runner.os != 'Windows'
      id: run_ctest_unix
      working-directory: ${{ github.workspace }}/${{ inputs.build_dir }}
      shell: bash
      continue-on-error: true
      run: |
        . ./conanbuild.sh
        
        # Fix for missing ctest/cpack in PATH
        if ! command -v ctest &> /dev/null && command -v cmake &> /dev/null; then
          CMAKE_REAL_PATH=$(readlink -f "$(command -v cmake)")
          CMAKE_DIR=$(dirname "$CMAKE_REAL_PATH")
          export PATH="$CMAKE_DIR:$PATH"
          echo "Added cmake dir to PATH: $CMAKE_DIR"
        fi
        
        echo "exit_code=0" >> $GITHUB_OUTPUT
        
        EX_REGEX="${{ inputs.exclude_regex }}"
        if [ -n "$EX_REGEX" ] && [ "$EX_REGEX" != '""' ]; then
          ctest --output-on-failure -C Release -j ${{ inputs.ctest_parallel_level }} -E "$EX_REGEX" || echo "exit_code=$?" >> $GITHUB_OUTPUT
        else
          ctest --output-on-failure -C Release -j ${{ inputs.ctest_parallel_level }} || echo "exit_code=$?" >> $GITHUB_OUTPUT
        fi

    # --- CTEST (WINDOWS) ---
    - name: Run CTest (Windows)
      if: runner.os == 'Windows'
      id: run_ctest_windows
      working-directory: ${{ github.workspace }}/${{ inputs.build_dir }}
      shell: cmd
      continue-on-error: true
      env:
        RUBYOPT: -Eutf-8
      run: |
        call conanbuild.bat
        echo exit_code=0 >> %GITHUB_OUTPUT%
        set "exclude_regex=${{ inputs.exclude_regex }}"
        if defined exclude_regex (
          ctest --output-on-failure -C Release --parallel ${{ inputs.ctest_parallel_level }} -E "%exclude_regex%"
        ) else (
          ctest --output-on-failure -C Release --parallel ${{ inputs.ctest_parallel_level }}
        )
        if %errorlevel% neq 0 (
          echo exit_code=%errorlevel% >> %GITHUB_OUTPUT%
        )

    - name: Set CTest Exit Code
      id: run_ctest
      shell: bash
      run: |
        if [ "${{ runner.os }}" == "Windows" ]; then
          echo "exit_code=${{ steps.run_ctest_windows.outputs.exit_code }}" >> $GITHUB_OUTPUT
        else
          echo "exit_code=${{ steps.run_ctest_unix.outputs.exit_code }}" >> $GITHUB_OUTPUT
        fi

    - name: Upload triage artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: triage-${{ inputs.platform_name }}-${{ github.sha }}
        path: |
          ${{ github.workspace }}/${{ inputs.build_dir }}/.ninja_log
          ${{ github.workspace }}/${{ inputs.build_dir }}/CTestTestfile.cmake
